### PR TITLE
Enable bitcode build options

### PR DESCRIPTION
**Pull request by LuoLee**
Add bitcode build options for #16 .

### CODE REVIEW

**Comment by spindleredmer** [comment]
Do you think it would be better to maybe have bitcode on by default?

**Comment by LuoLee** [comment]
Yes, enable bitcode by default may be better, but this will cause the framework to large.
If enable it by default, I suggest remove the pre-built framework from repo because of some developer may stay in poor network environment.

**Comment by spindleredmer** [comment]
The prebuild framework is needed because that is used in the Cocoapod, so I don't think it can't be removed.

**Comment by LuoLee** [comment]
Enable the bitcode by default.

**Pull request merged**
