### PR TITLE
Refactor build script

### PR DESCRIPTION
**Pull request by spindleredmer**

### CODE REVIEW

**Comment by spindleredmer** [comment]
@smolskyaleksey: Here is the refactor to compile, h264, ssl, opus into pjsip

**Comment by smolskyaleksey** [comment]
Great job! But I did not find any info about opus and H264.

**Comment by spindleredmer** [comment]
In the Vialerbuild file there is the code for the build.
If you type ./vialerbuild help you can see on how to use the script.

**Comment by smolskyaleksey** [comment]
In current https://github.com/VoIPGRID/Vialer-pjsip-iOS/blob/develop/vialerbuild implementation these are no any info about it.

**Comment by spindleredmer** [comment]
Correct, this is a review pull request for the branch feature/refactor-build-script-3072.
After it is approved for merger the it will be available in the develop branch

**Pull request merged**
